Output demo.gif

# Settings
Set Shell "bash"
Set FontSize 14
Set WindowBar Colorful
Set LineHeight 1.6
Set Padding 15
Set Width 1050
Set Height 500
Set TypingSpeed 100ms

# --- Demo starts ---
Type "python3 chatbot.py" Sleep 300ms Enter Sleep 2s

Type "no" Sleep 300ms Enter Sleep 2s

Type "yes" Sleep 300ms Enter Sleep 2s

Type "abc" Sleep 300ms Enter Sleep 2s

Type "22222" Sleep 300ms Enter Sleep 2s

Type "34567" Sleep 300ms Enter Sleep 2s

Type "yes" Sleep 300ms Enter Sleep 4s